/**********************************************************************************************************************
 * \file Cpu0_Main.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/
#include "Ifx_Types.h"
#include "IfxCpu.h"
#include "IfxScuWdt.h"
#include "ADC_Single_Channel.h"
#include "Bsp.h"
#include "ASCLIN_UART.h"
#include "IfxPort.h"
#include "GPT12_Timer_Interrupt.h"


#define TEST_PIN2                      &MODULE_P00, 0

#define WAIT_TIME   1000             /* Number of milliseconds to wait between each conversion                       */
#define alpha                       0.2
#define TEST_PIN1                   &MODULE_P02, 0
float prevX =0;
IfxCpu_syncEvent g_cpuSyncEvent = 0;
float adc_value ;
float Low_pass_fillter2 = 0;
float x_LPF = 0;
float servo = 0;


    union
    {
        int data;
        char bytedata[4];
    } m_adc_value;

float Low_pass_fillter(float x)
    {


        x_LPF = alpha * prevX + (1 - alpha) * x;
        prevX = x_LPF;

           return x_LPF;

    }

int core0_main(void)
{
    IfxCpu_enableInterrupts();
    
    /* !!WATCHDOG0 AND SAFETY WATCHDOG ARE DISABLED HERE!!
     * Enable the watchdogs and service them periodically if it is required
     */
    IfxScuWdt_disableCpuWatchdog(IfxScuWdt_getCpuWatchdogPassword());
    IfxScuWdt_disableSafetyWatchdog(IfxScuWdt_getSafetyWatchdogPassword());
    
    /* Wait for CPU sync event */
    IfxCpu_emitEvent(&g_cpuSyncEvent);
    IfxCpu_waitEvent(&g_cpuSyncEvent, 1);
    
    /* Initialize a time variable */
    Ifx_TickTime ticksFor100ms = IfxStm_getTicksFromMilliseconds(BSP_DEFAULT_TIMER, WAIT_TIME);
    ///////////
    IfxPort_setPinModeOutput(TEST_PIN1, IfxPort_OutputMode_pushPull, IfxPort_OutputIdx_general);
    IfxPort_setPinModeOutput(TEST_PIN2, IfxPort_OutputMode_pushPull, IfxPort_OutputIdx_general);
    ///////////

     /* Initialize LEDs */
     initializeLEDs();

     /* Initialize VADC */
     vadcBackgroundScanInit();

     /* Start the background scan */
     vadcBackgroundScanRun();

     /* Initialize UART */
     init_ASCLIN_UART();

    while(1)
    {
        adc_value = indicateConversionValue();
        Low_pass_fillter2 = Low_pass_fillter(adc_value);

        servo = (Low_pass_fillter2/4095.0)+1.0;


        IfxPort_setPinState(TEST_PIN2,IfxPort_State_high);
        wait(servo*100000);
        IfxPort_setPinState(TEST_PIN2,IfxPort_State_low);
        wait((20-servo)*100000);



    }
    return (1);
}
